name: Build and Deploy WAR to Tomcat

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java and Maven
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        #distribution: 'adoptopenjdk'
        distribution: 'temurin'
        java-package: 'jdk'
        check-latest: false

    # - name: Set up Maven
    #   uses: actions/setup-java@v3
    #   with:
    #     maven-version: '3.8.1'

    # Step 3: Build the WAR file using Maven
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Set up Tomcat and deploy the WAR
    - name: Set up and deploy to Tomcat
      run: |
        # Download and extract Tomcat
        wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.33/bin/apache-tomcat-10.1.33.tar.gz
        tar -xzf apache-tomcat-10.1.33.tar.gz
        mv apache-tomcat-10.1.33 tomcat

        # Copy the WAR file to the webapps directory
        cp target/demo.war tomcat/webapps/

        # Start the Tomcat server
        # Start the Tomcat server
          chmod +x tomcat/bin/startup.sh
          tomcat/bin/startup.sh

    # Step 5: Upload the WAR artifact
    - name: Upload WAR artifact
      uses: actions/deploy-pages@v3
      with:
        name: java-app-war
        path: target/*.war
